# Generated by Django 4.2.16 on 2024-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
