# Generated by Django 4.2.16 on 2024-12-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apemapp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
